# 文件二：docker-build.yml（用于构建和推送Docker镜像）
---
name: 构建OpenWrt工具链Docker镜像

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # 每周日运行一次

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置QEMU
        uses: docker/setup-qemu-action@v2

      - name: 设置Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 登录到GitHub容器注册表
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 构建并推送Docker镜像
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./openwrt-toolchain.dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/openwrt-toolchain:latest
            ghcr.io/${{ github.repository_owner }}/openwrt-toolchain:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
