name: "3. Compile OpenWrt Firmware"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["2. Prepare OpenWrt Compile"]
    types:
      - completed

env:
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: false
  TZ: Asia/Shanghai

jobs:
  compile:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout
      uses: actions/checkout@main

    # 获取上一个工作流的运行ID
    - name: Get Previous Workflow Run ID
      id: get-run-id
      uses: actions/github-script@v6
      with:
        script: |
          const workflows = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'prepare-compile.yml',
            status: 'success',
            per_page: 1
          });
          if (workflows.data.workflow_runs.length > 0) {
            core.setOutput('run_id', workflows.data.workflow_runs[0].id);
          } else {
            core.setFailed('No successful workflow run found');
          }

    # 下载构件
    - name: Download Build Files
      uses: actions/download-artifact@v4
      with:
        name: openwrt-build-files-${{ steps.get-run-id.outputs.run_id }}
        path: openwrt
      
    # 验证下载
    - name: Verify Download
      run: |
        if [ ! -d "openwrt" ]; then
          echo "Error: Build files download failed!"
          exit 1
        fi
        echo "OpenWrt directory contents:"
        ls -la openwrt/
        echo "Directory size:"
        du -sh openwrt/

    - name: Set Permissions
      run: |
        chmod -R +x openwrt/scripts
        chmod -R +x openwrt/target
        ls -la openwrt/scripts
        ls -la openwrt/target

    # 其余步骤保持不变...
