name: "2. Prepare OpenWrt Compile"

# ... (前面的配置保持不变) ...

    - name: Upload Build Files
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt_Build_Files_$(date +"%Y%m%d")  # 使用日期作为构件名
        path: |
          openwrt
          openwrt/dl
          openwrt/build_dir
          openwrt/staging_dir
        retention-days: 1
