name: "3. Compile OpenWrt Firmware"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["2. Prepare OpenWrt Compile"]
    types:
      - completed

env:
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  TZ: Asia/Shanghai
  FORCE: 1

jobs:
  compile:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true
        docker-images: true

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python3-pip python3-distutils python3-setuptools unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
        sudo ln -sf /usr/bin/python3 /usr/bin/python

    - name: Setup Python
      run: |
        python3 -m pip install --upgrade pip
        pip3 install setuptools distutils-pytest
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1

    - name: Checkout
      uses: actions/checkout@main

    - name: Download Build Files
      uses: actions/download-artifact@v4
      with:
        name: OpenWrt_Files
        path: openwrt
        repository: ${{ github.repository }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}

    - name: Set Permissions
      run: |
        chmod -R +x openwrt/scripts
        chmod -R +x openwrt/target

    - name: Verify Environment
      run: |
        echo "Python version:"
        python3 --version
        echo "Python path:"
        which python3
        echo "Python modules:"
        pip3 list
        echo "System information:"
        uname -a
        echo "Environment variables:"
        env

    - name: Compile firmware
      id: compile
      run: |
        cd openwrt
        echo "Starting compilation with FORCE=1"
        export FORCE=1
        make defconfig
        make -j$(nproc) FORCE=1 || make -j1 V=s FORCE=1
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_Firmware
        path: ${{ env.FIRMWARE }}
        retention-days: 7

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 1
        keep_minimum_runs: 3
