name: "3. Compile OpenWrt Firmware"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["2. Prepare OpenWrt Compile"]
    types:
      - completed

env:
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  TZ: Asia/Shanghai

jobs:
  compile:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        swap-storage: true
        docker-images: true

    - name: Setup Python Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-dev python3-pip python3-setuptools
        sudo apt-get install -y python3-distutils-extra python-is-python3

    - name: Checkout
      uses: actions/checkout@main

    - name: Download Build Files
      uses: actions/download-artifact@v4
      with:
        name: OpenWrt_Files
        path: ./
        repository: ${{ github.repository }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}

    - name: Check Directory Structure
      run: |
        echo "Current directory contents:"
        ls -la
        echo "openwrt directory contents (if exists):"
        ls -la openwrt || echo "openwrt directory not found"

    - name: Set Permissions
      run: |
        if [ ! -d "openwrt" ]; then
          echo "Creating openwrt directory..."
          mkdir -p openwrt
          echo "Moving files to openwrt directory..."
          mv * openwrt/ 2>/dev/null || true
          mv .* openwrt/ 2>/dev/null || true
        fi
        
        echo "Setting permissions..."
        chmod -R +x openwrt/scripts || echo "Warning: Could not set permissions for scripts"
        chmod -R +x openwrt/target || echo "Warning: Could not set permissions for target"
        
        echo "Final directory structure:"
        ls -la
        ls -la openwrt/

    - name: Compile firmware
      id: compile
      run: |
        cd openwrt
        echo "Starting compilation with $(nproc) threads"
        FORCE=1 make -j$(nproc) || FORCE=1 make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_Firmware
        path: ${{ env.FIRMWARE }}
        retention-days: 7

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 1
        keep_minimum_runs: 3
