name: "3. Compile OpenWrt Firmware"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["2. Prepare OpenWrt Compile"]
    types:
      - completed

env:
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: false
  TZ: Asia/Shanghai

jobs:
  compile:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    # 修改缓存恢复策略
    - name: Restore OpenWrt Cache
      uses: actions/cache@v3
      with:
        path: |
          openwrt
          openwrt/dl
          openwrt/build_dir
          openwrt/staging_dir
        # 使用更通用的恢复键模式
        key: openwrt-build-${{ github.sha }}
        restore-keys: |
          openwrt-build-
          openwrt-source-

    # 添加调试信息
    - name: Debug Info
      run: |
        pwd
        ls -la
        if [ -d "openwrt" ]; then
          echo "OpenWrt directory exists"
          ls -la openwrt
        else
          echo "OpenWrt directory not found"
          echo "Current directory contents:"
          ls -la
        fi

    # 其余步骤保持不变...
