name: "2. Prepare OpenWrt Compile"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["1. Prepare OpenWrt Environment"]
    types:
      - completed

env:
  CONFIG_FILE: .config
  DIY_P2_SH: diy-part2.sh
  TZ: Asia/Shanghai

jobs:
  prepare-compile:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    # 恢复第一个工作流的缓存
    - name: Restore OpenWrt Source Cache
      uses: actions/cache@v3
      with:
        path: openwrt
        key: openwrt-source-${{ github.sha }}
        restore-keys: |
          openwrt-source-

    - name: Load custom configuration
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: Download package
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    # 保存编译准备阶段的缓存
    - name: Cache OpenWrt Build Files
      uses: actions/cache@v3
      with:
        path: |
          openwrt
          openwrt/dl
          openwrt/build_dir
          openwrt/staging_dir
        key: openwrt-build-${{ github.sha }}
        restore-keys: |
          openwrt-build-
