name: "2. Prepare OpenWrt Compile"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["1. Prepare OpenWrt Environment"]
    types:
      - completed

env:
  CONFIG_FILE: .config
  DIY_P2_SH: diy-part2.sh
  TZ: Asia/Shanghai

jobs:
  prepare-compile:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout
      uses: actions/checkout@main

    # 恢复第一个工作流的缓存
    - name: Restore OpenWrt Source Cache
      uses: actions/cache@v3
      with:
        path: openwrt
        key: openwrt-source-${{ github.sha }}
        restore-keys: |
          openwrt-source-

    - name: Load custom configuration
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: Download package
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    # 更新到 v4 版本
    - name: Upload Build Files
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-build-files
        path: |
          openwrt
          openwrt/dl
          openwrt/build_dir
          openwrt/staging_dir
        retention-days: 1
