name: Package Download

on:
  repository_dispatch:
    types: [package_download]

jobs:
  package_download:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Download package
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Trigger compile and upload workflow
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/tikkacn/openwrt-new-rom/dispatches \
          -d '{"event_type":"compile_upload"}'