name: OpenWRT固件编译（Python依赖完全修复版）
 
on:
  workflow_dispatch:
 
env:
  REPO_URL: https://github.com/coolsnowwolf/lede  
  REPO_BRANCH: master 
  PYTHON_VER: "3.10"
 
jobs:
  env-setup:
    runs-on: ubuntu-22.04 
    steps:
      - name: 设置Python环境 
        run: |
          sudo apt-get update 
          # 安装完整Python套件 
          sudo apt-get install -y \
          python${{ env.PYTHON_VER }} \
          python${{ env.PYTHON_VER }}-dev \
          python${{ env.PYTHON_VER }}-distutils \
          python${{ env.PYTHON_VER }}-venv \
          python3-setuptools 
 
          # 修复系统链接 
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${{ env.PYTHON_VER }} 100 
          sudo ln -sf /usr/lib/python${{ env.PYTHON_VER }}/dist-packages /usr/lib/python3/dist-packages 
          
          # 验证环境 
          python3 -c "import distutils, sys; print(f'Python {sys.version}\nDistutils 路径: {distutils.__file__}')"
 
  prepare:
    needs: env-setup 
    runs-on: ubuntu-22.04 
    steps:
      - name: 检出仓库 
        uses: actions/checkout@v4 
 
      - name: 安装编译依赖 
        run: |
          sudo apt-get install -y \
          build-essential ccache flex gawk gettext git libncurses-dev libssl-dev \
          zlib1g-dev gcc g++ make unzip rsync wget curl 
 
      - name: 克隆源码 
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt 
          [ -f feeds.conf.default  ] && cp feeds.conf.default  openwrt/feeds.conf.default  
 
      - name: 应用配置 
        run: |
          chmod +x diy-part*.sh 
          cd openwrt 
          ../diy-part1.sh  
          ./scripts/feeds update -a 
          ./scripts/feeds install -a 
          [ -f ../.config ] && cp ../.config .
          ../diy-part2.sh  
 
      - name: 上传预处理代码 
        uses: actions/upload-artifact@v4 
        with:
          name: openwrt-src 
          path: openwrt 
 
  build:
    needs: prepare 
    runs-on: ubuntu-22.04 
    steps:
      - name: 下载源码 
        uses: actions/download-artifact@v4 
        with:
          name: openwrt-src 
          path: openwrt 
 
      - name: 编译环境验证 
        run: |
          export PYTHONPATH=/usr/lib/python${{ env.PYTHON_VER }}/dist-packages 
          cd openwrt 
          make defconfig PYTHON=python3 
 
      - name: 执行编译 
        timeout-minutes: 120 
        run: |
          cd openwrt 
          make -j$(($(nproc) + 1)) download 
          make -j$(nproc) V=s PYTHON=python3 
 
      - name: 打包产物 
        run: |
          cd openwrt/bin/targets/x86/64/
          sha256sum *img* > sha256sums 
          ls -lh 
 
      - name: 上传固件 
        uses: actions/upload-artifact@v4 
        with:
          name: openwrt-x86_64-$(date +%s)
          path: openwrt/bin/targets/x86/64/* 
 
  release:
    needs: build 
    runs-on: ubuntu-22.04 
    steps:
      - name: 创建发布版本 
        uses: softprops/action-gh-release@v1 
        with:
          tag_name: x86_64-$(date +%Y%m%d-%H%M)
          files: |
            openwrt-x86_64-*/openwrt-x86-64-generic-squashfs-combined-efi.img.gz  
            openwrt-x86_64-*/sha256sums 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
