name: OpenWRT固件编译（最终修复版）
 
on:
  workflow_dispatch:
  push:
    branches: [ main ]
 
env:
  REPO_URL: https://github.com/coolsnowwolf/lede  
  PYTHON_VER: "3.10"
 
jobs:
  build:
    runs-on: ubuntu-22.04 
    timeout-minutes: 120 
    steps:
      - name: 检出仓库（含.config）
        uses: actions/checkout@v4 
        with:
          path: custom-src 
 
      - name: 配置Python环境 
        run: |
          sudo apt-get update 
          sudo apt-get install -y \
          python${{ env.PYTHON_VE }} \
          python${{ env.PYTHON_VER }}-distutils \
          python${{ env.PYTHON_VER }}-venv 
 
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${{ env.PYTHON_VER }} 100 
          sudo ln -sfv /usr/lib/python${{ env.PYTHON_VER }}/dist-packages /usr/lib/python3/dist-packages 
 
      - name: 安装编译依赖 
        run: |
          sudo apt-get install -y \
          build-essential ccache flex gawk gettext git libncurses-dev \
          libssl-dev zlib1g-dev gcc g++ make unzip rsync wget curl 
 
      - name: 准备源码 
        run: |
          git clone --depth 1 ${{ env.REPO_URL }} openwrt 
          # 同步自定义配置 
          [ -f custom-src/.config ] && cp custom-src/.config openwrt/
          [ -f custom-src/feeds.conf.default  ] && cp custom-src/feeds.conf.default  openwrt/
 
      - name: 应用用户配置 
        run: |
          cd openwrt 
          if [ -f .config ]; then 
            echo "✅ 检测到自定义配置文件"
            make oldconfig 
          else 
            echo "⚠️ 使用默认配置"
            make defconfig 
          fi 
 
      - name: 执行编译 
        env:
          FORCE_UNSAFE_CONFIGURE: "1"
          PYTHONPATH: "/usr/lib/python${{ env.PYTHON_VER }}/dist-packages"
        run: |
          cd openwrt 
          ./scripts/feeds update -a 
          ./scripts/feeds install -a 
          make -j$(($(nproc) + 1)) download 
          make -j$(nproc) V=s FORCE=1 
 
      - name: 打包固件 
        run: |
          cd openwrt/bin/targets/x86/64/
          sha256sum *img* > sha256sums 
          ls -lh 
 
      - name: 上传产物 
        uses: actions/upload-artifact@v4 
        with:
          name: openwrt-$(date +%Y%m%d-%H%M)
          path: openwrt/bin/targets/x86/64/*
