name: OpenWRT固件编译（Python依赖修复版）
 
on:
  workflow_dispatch:
 
env:
  REPO_URL: https://github.com/coolsnowwolf/lede  
  REPO_BRANCH: master 
  TARGET_ARCH: x86/64 
 
jobs:
  prepare:
    runs-on: ubuntu-22.04 
    steps:
      - name: 检出仓库 
        uses: actions/checkout@v4 
 
      - name: 安装核心依赖 
        run: |
          sudo apt-get update 
          sudo apt-get install -y \
          build-essential ccache flex gawk gettext git libncurses-dev libssl-dev \
          python3 python3-dev python3-distutils python3-setuptools python3-venv \
          zlib1g-dev gcc g++ make unzip rsync wget curl 
 
      - name: 验证Python环境 
        run: |
          python3 -c "import distutils.util,  sysconfig; print('Python路径:', sysconfig.get_path('purelib'))" 
          python3 -m pip install --upgrade wheel setuptools 
 
      - name: 克隆源码 
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt 
          [ -f feeds.conf.default  ] && cp feeds.conf.default  openwrt/feeds.conf.default  
 
      - name: 应用自定义配置 
        run: |
          chmod +x diy-part*.sh 
          cd openwrt 
          ../diy-part1.sh  
          ./scripts/feeds update -a 
          ./scripts/feeds install -a 
          [ -f ../.config ] && cp ../.config .
          ../diy-part2.sh  
 
      - name: 缓存源码 
        uses: actions/upload-artifact@v4 
        with:
          name: openwrt-src 
          path: openwrt 
 
  build:
    needs: prepare 
    runs-on: ubuntu-22.04 
    env:
      CCACHE_DIR: /tmp/ccache 
    steps:
      - name: 恢复源码 
        uses: actions/download-artifact@v4 
        with:
          name: openwrt-src 
          path: openwrt 
 
      - name: 配置编译环境 
        run: |
          cd openwrt 
          echo 'CONFIG_TARGET_x86=y' >> .config 
          echo 'CONFIG_TARGET_x86_64=y' >> .config 
          make defconfig 
 
      - name: 编译固件 
        timeout-minutes: 90 
        run: |
          cd openwrt 
          make -j$(($(nproc) + 1)) download 
          make -j$(nproc) V=s 
 
      - name: 打包产物 
        run: |
          cd openwrt/bin/targets/x86/64/
          sha256sum *img* > sha256sums 
          ls -lh 
 
      - name: 上传固件 
        uses: actions/upload-artifact@v4 
        with:
          name: openwrt-x86_64 
          path: openwrt/bin/targets/x86/64/* 
 
  release:
    needs: build 
    runs-on: ubuntu-22.04 
    steps:
      - name: 发布版本 
        uses: softprops/action-gh-release@v1 
        with:
          tag_name: x86_64-$(date +%Y%m%d)
          files: |
            openwrt-x86_64/openwrt-x86-64-generic-squashfs-combined-efi.img.gz  
            openwrt-x86_64/sha256sums 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
