name: OpenWRT固件编译（x86_64专用版）
 
on:
  repository_dispatch:
  workflow_dispatch:
 
env:
  REPO_URL: https://github.com/coolsnowwolf/lede  
  REPO_BRANCH: master 
  FEEDS_CONF: feeds.conf.default  
  CONFIG_FILE: .config 
  DIY_P1_SH: diy-part1.sh  
  DIY_P2_SH: diy-part2.sh  
  TZ: Asia/Shanghai 
 
jobs:
  prepare:
    runs-on: ubuntu-22.04 
    steps:
      - name: 检出代码库 
        uses: actions/checkout@v4 
 
      - name: 安装编译依赖 
        env:
          DEBIAN_FRONTEND: noninteractive 
        run: |
          sudo apt-get update -y 
          sudo apt-get full-upgrade -y 
          sudo apt-get install -y build-essential ccache ecj fastjar file flex \
          g++ gawk gettext git java-propose-classpath libelf-dev libncurses5-dev \
          libncursesw5-dev libssl-dev python3 python2.7 python3-distutils qemu-utils \
          rsync subversion unzip zlib1g-dev wget time 
 
      - name: 克隆OpenWRT源码 
        run: |
          git clone --depth=1 $REPO_URL -b $REPO_BRANCH openwrt 
          [ -f $FEEDS_CONF ] && cp $FEEDS_CONF openwrt/feeds.conf.default  
 
      - name: 执行自定义配置 
        run: |
          chmod +x $DIY_P1_SH $DIY_P2_SH 
          cd openwrt 
          ../$DIY_P1_SH 
          ./scripts/feeds update -a 
          ./scripts/feeds install -a 
          [ -f ../$CONFIG_FILE ] && cp ../$CONFIG_FILE .config 
          ../$DIY_P2_SH 
 
      - name: 上传源码快照 
        uses: actions/upload-artifact@v4 
        with:
          name: openwrt-src 
          path: openwrt 
 
  build:
    needs: prepare 
    runs-on: ubuntu-22.04 
    steps:
      - name: 获取源码 
        uses: actions/download-artifact@v4 
        with:
          name: openwrt-src 
          path: openwrt 
 
      - name: 编译固件 
        run: |
          cd openwrt 
          make defconfig 
          make -j$(($(nproc) + 1)) download 
          make -j$(nproc) V=s 
 
      - name: 归档编译产物 
        uses: actions/upload-artifact@v4 
        with:
          name: openwrt-bin 
          path: openwrt/bin/targets/x86/64/*.img.gz  
 
  deploy:
    needs: build 
    runs-on: ubuntu-22.04 
    steps:
      - name: 下载固件 
        uses: actions/download-artifact@v4 
        with:
          name: openwrt-bin 
          path: firmware 
 
      - name: 创建版本发布 
        uses: softprops/action-gh-release@v1 
        with:
          tag_name: build-$(date +%Y%m%d%H%M)
          files: |
            firmware/*.img.gz  
            firmware/sha256sums 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
