name: 拆包编译

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  TZ: Asia/Shanghai
  LOG_PATH: build_logs

jobs:
  build-toolchain:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create Log Directory
      run: mkdir -p ${{ env.LOG_PATH }}

    - name: Initialize Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        {
          echo "=== Environment Initialization Started at $(date) ==="
          # 首先更新软件源
          sudo -E apt-get update
          
          # 添加必要的软件源
          sudo -E apt-get install -y software-properties-common
          sudo -E add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe"
          sudo -E add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-updates main universe"
          
          # 再次更新软件源
          sudo -E apt-get update
          
          # 安装基本开发工具
          sudo -E apt-get install -y \
            build-essential \
            clang \
            flex \
            g++ \
            gawk \
            gcc-multilib \
            g++-multilib \
            gettext \
            git \
            libncurses5-dev \
            libssl-dev \
            python3 \
            python3-distutils \
            python3-pip \
            zlib1g-dev \
            lib32gcc-s1 \
            rsync \
            unzip \
            file \
            wget
            
          echo "=== Environment Initialization Completed at $(date) ==="
        } 2>&1 | tee -a ${{ env.LOG_PATH }}/toolchain.log

    - name: Clone Source Code
      run: |
        {
          echo "=== Source Code Clone Started at $(date) ==="
          df -h
          git clone $REPO_URL -b $REPO_BRANCH openwrt
          cd openwrt
          ls -la
          chmod +x scripts/feeds
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          echo "=== Source Code Clone Completed at $(date) ==="
        } 2>&1 | tee -a ${{ env.LOG_PATH }}/toolchain.log

    # ... 其余步骤保持不变
